# errores.py

ERRORES = {
    "Error021": "La IPS primaria no existe",
    "Error220": "Número de identificación con caracteres no permitidos",
    "Error676": "La longitud del número de identificación no corresponde con el tipo de identificación",
    "Error020": "La fecha de nacimiento es requerida",
    "Error421": "contenido en el campo FechaNacimiento  no válido",
    "Error677": "No se permite el registro de estos comodines en Fecha Nacimiento",
    "Error120": "Fecha Nacimiento es mayor a la fecha de corte",
    "Error030": "Si registra 1, 2 ó 21 en la variable Gestante, el sexo debe ser F",
    "Error222": "Si la edad es menor de 10 años o mayor o igual de 60 años, Gestación No aplica",
    "Error223": "Si el sexo es Femenino y la edad está entre 10 años hasta 59 años, debe registrar un valor diferente de 0-no aplica en Gestante.",
    "Error244": "Si no es gestante, las variables relacionadas con la gestación deben registrar el valor equivalente a 'No aplica'",
    "Error379": "Si es gestante, las variables relacionadas con la gestación deben registrar un dato diferente a 'No aplica'",
    "Error500": "Error en valores permitidos -Sífilis Gestacional o congénita",
    "Error503": "Si registra Resultado prueba mini-mental state, debe registrar una Fecha de consulta de valoración integral válida",
    "Error504": "Error en valores permitidos -Resultado del test minimental state",
    "Error227": "El valor del Resultado prueba mini-mental state registrado no es acorde al rango de edad ",
    "Error505": "Error en valores permitidos - Hipotiroidismo Congénito",
    "Error232": "Si es sintomático respiratorio, el resultado de baciloscopia diagnóstica debe ser diferente a 4 y registrar fecha válida o comodín de no realización",
    "Error506": "Si no es Sintomático respiratorio, registre no en el  Resultado de baciloscopia de diagnóstico y registre no aplica en la Fecha de toma",
    "Error507": "Riesgo no evaluado en Sintomático respiratorio, registre riesgo no evaluado en resultado baciloscopia y sin dato en fecha baciloscopia",
    "Error508": "Si la edad es menor a 12 años, el registro de Consumo de tabaco no aplica.",
    "Error509": "Error en valores permitidos -Lepra",
    "Error510": "Error en valores permitidos -Obesidad o Desnutrición Proteico Calórica",
    "Error037": "Si registra 4, 5 o 21 en Resultado del tacto rectal, el sexo debe ser M",
    "Error038": "Si es hombre menor de 40 años, debe registrar  no aplica en el resultado y la fecha del tacto rectal",
    "Error237": "Si registra fecha del tacto rectal, debe registrar el resultado del tacto rectal, el sexo debe ser M y la edad mayor o igual a 40 años",
    "Error512": "Si Resultado de tacto rectal es riesgo no evaluado, en la fecha debe registrar alguno de los comodines que indican no realización o sin dato",
    "Error513": "Si es sexo F, debe registrar no aplica en la fecha y el resultado de tacto rectal",
    "Error514": "Error en valores permitidos - Resultado tacto rectal",
    "Error515": "Error en valores permitidos - Acido fólico preconcepcional",
    "Error516": "Si registró Fecha de la prueba sangre oculta en materia fecal válida, debe registrar Resultado de la prueba sangre oculta en materia fecal",
    "Error517": "Si registró comodín de no realización o sin dato en Fecha prueba sangre oculta en materia fecal, la edad debe ser entre 50-75 y el Resultado debe ser 21",
    "Error518": "Registre no aplica en Fecha de prueba sangre oculta en materia fecal, a los menores de 50 años ó mayores de 75 años sin riesgo identificado",
    "Error519": "Error en valores permitidos - Resultado test de sangre oculta en materia fecal",
    "Error520": "Error en valores permitidos -Enfermedad mental",
    "Error521": "Error en valores permitidos -Cáncer de Cérvix",
    "Error524": "Si registra Agudeza visual lejana ojo izquierdo, debe registrar Fecha de agudeza visual válida",
    "Error525": "Si registró un comodín que indica no realización o sin dato en Fecha de agudeza visual, registre 21 en Agudeza visual lejana ojo izquierdo",
    "Error526": "Si es menor a 3 años, debe registrar no aplica en las variables de agudeza visual lejana ojo izquierdo y fecha de agudeza visual",
    "Error527": "Error en valores permitidos - Agudeza visual lejana ojo izquierdo ",
    "Error528": "Si registra Agudeza visual lejana ojo derecho, debe registrar Fecha de agudeza visual válida",
    "Error529": "Si registró un comodín que indica no realización o sin dato en Fecha de agudeza visual, registre 21 en Agudeza visual lejana ojo derecho",
    "Error530": "Si es menor a 3 años, debe registrar no aplica en las variables de agudeza visual lejana ojo derecho y fecha de agudeza visual",
    "Error531": "Error en valores permitidos - Agudeza visual lejana ojo derecho ",
    "Error121": "Fecha peso es mayor a la fecha de corte",
    "Error171": "Fecha peso es menor a la fecha de nacimiento",
    "Warning674": "Verifique el comodín 1800-01-01, registre una fecha válida.",
    "Error422": "contenido en el campo FechaPeso  no válido",
    "Error381": "No se permite el registro de estos comodines en Fecha peso",
    "Error041": "Si no registra el peso de la persona no debe registrar fecha de medición",
    "Error680": "El peso de los niños menores de 2 años debe ser mayor o igual a 1 kg y menor o igual a 15 kg",
    "Error681": "El peso de los niños de 2 a 4 años debe ser mayor o igual a 3 kg y menor o igual a 25 kg",
    "Error682": "El peso de los niños de 5 a 12 años debe ser mayor o igual a 9 kg y menor o igual a 80 kg",
    "Error683": "El peso de los adolescentes de 13 a 17 años debe ser mayor o igual a 30 kg y menor o igual a 80 kg",
    "Error684": "El peso de los adyltos matores de 18 años debe ser mayor o igual a 36 kg y menor o igual a 250 kg",
    "Error122": "Fecha talla es mayor a la fecha de corte",
    "Error172": "Fecha talla es menor a la fecha de nacimiento",
    "Warning675": "Verifique el comodín 1800-01-01, registre una fecha válida.",
    "Error423": "contenido en el campo FechaTalla  no válido",
    "Error382": "No se permite el registro de estos comodines en Fecha de la talla",
    "Error043": "Si no registra la talla de la persona no debe registrar fecha de medición",
    "Error685": "La talla de los niños menores de 2 años debe ser mayor o igual a 40 cm y menor o igual a 100 cm",
    "Error686": "La talla de los niños de 2 a 4 años debe ser mayor o igual a 70 cm y menor o igual a 110 cm",
    "Error687": "La talla de los niños de 5 a 12 años debe ser mayor o igual a 80 cm y menor o igual a 225 cm",
    "Error688": "La talla de los adolescentes de 13 a 17 años debe ser mayor o igual a 130 cm y menor o igual a 225 cm",
    "Error689": "La talla de los adultos mayores a 18 años debe ser mayor o igual a 130 cm y menor o igual a 225 cm",
    "Error170": "Fecha probable parto es menor a la fecha de nacimiento",
    "Error242": "Si registra fecha probable de parto no debe ser mayor a la fecha de corte más 280 días",
    "Error243": "Fecha probable de parto es menor o igual a fecha de primera consulta prenatal",
    "Error424": "contenido en el campo FechaProbableParto no válido",
    "Error380": "Comodín inválido - Fecha probable parto",
    "Error532": "El código país no es coherente con el tipo de identificación",
    "Error533": "Error en valores permitidos - Clasificación del riesgo gestacional",
    "Error534": "Si registró clasificación de riesgo gestac., registre una fecha válida en la primera consulta prenatal o en el último control prenatal de seguimiento",
    "Error535": "Si registra Fecha de colonoscopia válida, registre el resultado de colonoscopia de tamizaje",
    "Error536": "Si registró comodín de no realización o sin dato en Fecha de colonoscopia, la edad debe estar entre 50 y 75 y resultado de colonoscopia debe ser 21",
    "Error537": "Si registró comodín de no aplica en Fecha de colonoscopia, el resultado de colonoscopia debe ser 0 y la edad debe ser <= 50 ó > 75 años ",
    "Error538": "Error en valores permitidos - Resultado colonoscopia de tamizaje",
    "Error539": "Si registra Resultado de tamizaje auditivo neonatal, debe registrar fecha de tamizaje",
    "Error540": "Error en valores permitidos - Resultado de tamizaje auditivo neonatal",
    "Warning541": "Verifique la actividad -resultado tamizaje auditivo neonatal- reportada en población mayor a 30 días",
    "Error542": "Si Resultado de tamizaje auditivo neonatal es 21, debe registrar un comodín que indique no realización o sin dato en fecha de tamizaje",
    "Error543": "Si registra Resultado de tamizaje visual neonatal, debe registrar fecha de tamizaje",
    "Error544": "Error en valores permitidos - Resultado de tamizaje visual neonatal",
    "Warning545": "Verifique la actividad -resultado de tamizaje visual neonatal- reportada en población mayor a 30 días",
    "Error546": "Si Resultado de tamizaje visual neonatal es riesgo no evaluado, debe registrar un comodín que indique no realización o sin dato en fecha del tamizaje",
    "Error574": "Error en valores permitidos - DPT menores de 5 años",
    "Error548": "Si registra Resultado de tamizaje VALE, debe registrar Fecha de tamizaje VALE y ser menor a 13 años (hasta 12 años, 11 meses y 29 días)",
    "Error549": "Error en valores permitidos - Resultado de tamizaje VALE",
    "Error550": "Si Resultado de tamizaje VALE no aplica, debe registrar Fecha de tamizaje VALE  no aplica y ser mayor de 12 años",
    "Error551": "Si Resultado de tamizaje VALE es 21, debe ser menor a 13 años y registrar comodín que indique no realización o sin dato en fecha del tamizaje",
    "Error552": "Error en valores permitidos -Neumococo",
    "Error553": "Si registrar Fecha de tamizaje de hepatitis C, debe registrar un resultado de tamizaje para hepatitis C",
    "Error554": "Si registra un comodín que indique no realización o sin dato en Fecha de tamizaje, registre 21 en Resultado de tamizaje para hepatitis C",
    "Warning555": "Verifique la actividad -Resultado de tamizaje para hepatitis C- reportada en población nacida después de 1996",
    "Error556": "Si Fecha de tamizaje de Hepatitis C no aplica, Resultado de tamizaje no aplica.",
    "Error557": "Error en valores permitidos - Resultado de tamizaje para hepatitis C",
    "Error558": "Si registra Resultado de escala abreviada de desarrollo área de motricidad gruesa, debe registrar una fecha de consulta de valoración integral válida",
    "Error559": "Error en valores permitidos -Resultado de escala abreviada de desarrollo área de motricidad gruesa",
    "Error560": "Verifique el resultado de escala abreviada de desarrollo área de motricidad gruesa, de acuerdo a la edad",
    "Warning561": "Se reportó fecha consulta de valoración integral al niño de 0 a 7 años, sin reporte de Resultado escala abreviada desarrollo área motricidad gruesa",
    "Error562": "Si registra Resultado escala abreviada desarrollo área motricidad finoadaptativa, debe registrar una fecha de consulta de valoración integral válida",
    "Error563": "Error en valores permitidos -Resultado de escala abreviada de desarrollo área de motricidad finoadaptativa",
    "Error564": "Verifique el resultado de escala abreviada de desarrollo área de motricidad finoadaptativa, de acuerdo a la edad",
    "Warning565": "Se reportó fecha consulta de valoración integral a niño de 0 a 7 años, sin reporte de Resultado escala abreviada desarrollo motricidad finoadaptativa ",
    "Error566": "Si registra Resultado de escala abreviada de desarrollo área personal social, debe registrar una fecha de consulta de valoración integral válida",
    "Error567": "Error en valores permitidos -Resultado de escala abreviada de desarrollo área personal social",
    "Error568": "Verifique el resultado de escala abreviada de desarrollo área personal social, de acuerdo con la edad",
    "Warning569": "Se reportó fecha consulta de valoración integral a niño de 0 a 7 años, sin reporte de Resultado de escala abreviada de desarrollo área personal social",
    "Error570": "Si registra Resultado escala abreviada de desarrollo área motricidad audición lenguaje, registre una fecha de consulta de valoración integral válida",
    "Error571": "Error en valores permitidos -Resultado de escala abreviada de desarrollo área de motricidad audición lenguaje",
    "Error572": "Verifique el resultado de escala abreviada de desarrollo área de motricidad audición lenguaje, de acuerdo a la edad",
    "Warning573": "Se reportó fecha consulta de valoración integral a niño de 0 a 7 años, sin Resultado de escala abreviada de desarrollo área motricidad audic. lenguaje",
    "Error673": "Si el resultado de la técnica de inspección visual es positivo, debe registrar tratamiento.",
    "Error575": "Si el resultado de la técnica de inspección visual es negativo o usó otra técnica, debe registrar no aplica en tratamiento ablativo o escisión.",
    "Error047": "Si reporta Tratamiento ablativo o de escisión posterior a la realización técnica de inspección visual (Crioterapia o LETZ) , el sexo debe ser F",
    "Error576": "Error en valores permitidos -Tratamiento ablativo o de escisión posterior a la realización técnica de inspección visual (Crioterapia o LETZ)",
    "Error578": "Si registra Resultado de tamización con oximetría pre y post ductal, debe registrar la fecha del tamizaje",
    "Error579": "Error en valores permitidos - Resultado de tamización con oximetría pre y post ductal",
    "Warning580": "Verifique la actividad -resultado de tamizaje visual neonatal- reportada en población mayor a 30 días",
    "Error581": "Si Resultado de tamización con oximetría pre y pos ductual es 21, registre un comodín que indique no realización o sin dato en la fecha del tamizaje",
    "Error049": "Si registra Fecha de atención parto o cesárea, el sexo debe ser F",
    "Error123": "Fecha atención parto o cesárea es mayor a la fecha de corte del reporte",
    "Error173": "Fecha atención parto o cesárea es menor a la fecha de nacimiento",
    "Error294": "Si registra Fecha de atención parto ó cesárea, debe ser mayor o igual de 10 años y menor de 60 años",
    "Error296": "Si registra fecha de atención parto ó cesárea, debe registrar fecha de salida de atención parto o cesárea",
    "Error425": "contenido en el campo FechaPartoCesarea no válido",
    "Error383": "Comodín inválido - Fecha atención parto o cesárea",
    "Error050": "Si registra fecha de salida de atención de parto el sexo debe ser F",
    "Error124": " Fecha salida del parto o cesárea es mayor a la fecha de corte",
    "Error174": "Fecha salida del parto o cesárea es menor a la fecha de nacimiento",
    "Error299": "Si registra Fecha de salida de atención parto o cesárea, debe ser mayor o igual de 10 años y menor de 60 años",
    "Error300": "Fecha de salida de parto es menor a fecha de atención del parto",
    "Error301": "Si registra Fecha de salida de atención parto o cesárea, debe registrar Fecha de atención parto o cesárea",
    "Error426": "contenido en el campo FechaSalidaPartoCesarea  no válido",
    "Error384": "Comodín inválido - Fecha salida del parto o cesárea",
    "Error051": "Registre Fecha atención en salud para la promoción y apoyo de la lactancia materna no aplica a personas de sexo M con edad mayor a 7 meses",
    "Error125": "Fecha atención en salud para la promoción y apoyo de la lactancia materna es mayor a la fecha de corte del reporte",
    "Error175": "Fecha atención en salud para la promoción y apoyo de la lactancia materna es menor a la fecha de nacimiento",
    "Error385": "Comodín inválido - Fecha atención en salud para la promoción y apoyo de la lactancia materna",
    "Error427": "contenido en el campo fecha de atención para la consejería en lactancia materna  no válido",
    "Error583": "La atención en salud para la promoción y apoyo de la lactancia materna no aplica para la edad de la persona porque no es gestante",
    "Error126": "Fecha de consulta de valoración integral es mayor a la fecha de corte",
    "Error176": "Fecha de consulta de valoración integral es menor a la fecha de nacimiento",
    "Error447": "contenido en el campo Consulta de valoración integral no válido",
    "Error386": "Comodín inválido - Fecha de consulta de valoración integral",
    "Error304": "Verifique la actividad Fecha de Atención en salud para la asesoría en anticoncepción reportada en población menor de 10 años",
    "Error305": "Verifique la Fecha de Atención en salud para la asesoría en anticoncepción con reporte 'no aplica' en población mayor o igual de 10 años",
    "Error127": "La fecha de la Atención en salud para la asesoría en anticoncepción es mayor a la fecha de corte",
    "Error177": "La fecha de la Atención en salud para la asesoría en anticoncepción es menor a la fecha de nacimiento",
    "Error448": "contenido en el campo Fecha de atención para la asesoría en anticoncepción no válido",
    "Error387": "Comodín inválido - Atención en salud para la asesoría en anticoncepción",
    "Error309": "Si registra fecha de suministro de método anticonceptivo, debe registra un dato diferente a 0 en el suministro",
    "Warning307": "Si registra suministro de método, debe ser mayor o igual de 10 años y menor de 60 años",
    "Error308": "No es válido registrar no aplica en suministro de método anticonceptivo si la edad está entre 10 y 59 años ",
    "Error306": "Si resgistró no aplica (1845-01-01) en la fecha de suministro de método, debe registrar no aplica (0) en el método anticonceptivo suministrado. ",
    "Error128": "Fecha suministro método anticonceptivo es mayor a la fecha de corte del reporte",
    "Error178": "Fecha suministro método anticonceptivo es menor a la fecha de nacimiento",
    "Error428": "contenido en el campo FechaSuministroMetodoAnticonceptivo no válido",
    "Error388": "Comodín inválido - Fecha suministro método anticonceptivo",
    "Error318": "Fecha de ultimo control prenatal de seguimiento es menor a Fecha de primera consulta prenatal",
    "Error129": "Fecha de primera consulta prenatal es mayor a la fecha de corte",
    "Error179": "Fecha de primera consulta prenatal es menor a la fecha de nacimiento",
    "Error449": "contenido en el campo primera consulta prenatal no válido",
    "Error389": "Comodín inválido - Fecha de Primera Consulta Prenatal",
    "Error584": "Si registra Fecha de toma de glicemia basal, debe registrar el Resultado de glicemia basal",
    "Error585": "Si registró 1800-01-01, 1805-01-01, 1810-01-01, 1825-01-01, 1830-01-01 ó 1835-01-01 en Fecha Glicemia Basal, registre 998 en Resultado GB y viceversa",
    "Error586": "Registre no aplica en Fecha toma de glicemia y Resultado de glicemia, a los menores de 29 años sin riesgo cardiovascular identificado",
    "Error130": "Fecha de último control prenatal de seguimiento es mayor a la fecha de corte",
    "Error180": "Fecha de último control prenatal de seguimiento es menor a la fecha de nacimiento",
    "Error450": "contenido en el  UltimoControlPrenatal no válido",
    "Error390": "Comodín inválido - Fecha de último control prenatal de seguimiento",
    "Error587": "Error en valores permitidos -Suministro de ácido fólico en el control prenatal durante el periodo reportado",
    "Error588": "Error en valores permitidos -Suministro de sulfato ferroso en el control prenatal durante el periodo reportado",
    "Error589": "Error en valores permitidos -Suministro de carbonato de calcio en el control prenatal durante el periodo reportado",
    "Error131": "Fecha de valoración agudeza visual es mayor a la fecha de corte",
    "Error181": "Fecha de valoración agudeza visual es menor a la fecha de nacimiento",
    "Error590": "Si las variables Agudeza visual lejana ojo izquierdo y ojo derecho no aplican, debe registrar no aplica en Fecha de valoración de la agudeza visual ",
    "Error451": "contenido en el campo FechaValoracionAgudezaVisual no válido",
    "Error391": "Comodín inválido - Fecha de valoración de la agudeza visual",
    "Error132": "Fecha de tamizaje VALE es mayor a la fecha de corte",
    "Error182": "Fecha de tamizaje VALE es menor a la fecha de nacimiento",
    "Error452": "contenido en el campo Fecha de tamizaje VALE no válido",
    "Error392": "Comodín inválido - Fecha de tamizaje VALE",
    "Error133": "Fecha del tacto rectal es mayor a la fecha de corte",
    "Error183": "Fecha del tacto rectal es menor a la fecha de nacimiento",
    "Error453": "contenido en el campo Fecha del tacto rectal no válido",
    "Error393": "Comodín inválido - Fecha del tacto rectal",
    "Error134": "Fecha tamización con oximetría pre y post ductal es mayor a la fecha de corte",
    "Error184": "Fecha tamización con oximetría pre y post ductal es menor a la fecha de nacimiento",
    "Error454": "contenido en el campo Fecha de tamización con oximetría pre y post ductal no válido",
    "Error394": "Comodín inválido - Fecha tamización con oximetría pre y post ductal",
    "Error135": "Fecha de realización colonoscopia tamizaje es mayor a la fecha de corte",
    "Error185": "Fecha de realización colonoscopia tamizaje es menor o igual a la fecha de nacimiento",
    "Error455": "contenido en el campo Fecha realización colonoscopia tamizaje no válido",
    "Error395": "Comodín inválido - Fecha de realización colonoscopia tamizaje",
    "Error136": "Fecha de la prueba de sangre oculta en materia fecal (tamizaje Ca de colon) es mayor a la fecha de corte",
    "Error186": "Fecha de la prueba de sangre oculta en materia fecal (tamizaje Ca de colon) es menor a la fecha de nacimiento",
    "Error456": "Fecha de la prueba de sangre oculta en materia fecal no válido",
    "Error396": "Comodín inválido - Fecha de la prueba de sangre oculta en materia fecal (tamizaje Ca de colon)",
    "Error591": "Error en valores permitidos -Consulta de Psicología",
    "Error457": "contenido en el campo ConsultaPsicología no válido",
    "Error138": "Fecha de tamizaje auditivo neonatal es mayor a la fecha de corte",
    "Error188": "Fecha de tamizaje auditivo neonatal es menor a la fecha de nacimiento",
    "Error458": "contenido en el campo Fecha de tamizaje auditivo neonatal no válido",
    "Error398": "Comodín inválido - Fecha de tamizaje auditivo neonatal",
    "Error063": "Verifique la edad de la persona con Suministro de  fortificación casera, según normatividad vigente",
    "Error592": "Error en valores permitidos -Suministro de  fortificación casera en la primera Infancia.",
    "Error328": "No es válido registrar 'No aplica' en Suministro de fortificación casera para la edad reportada, revise la normatividad vigente.",
    "Error064": "Verifique la edad de la persona con Suministro de Vitamina A en la primera Infancia, según normatividad vigente",
    "Error593": "Error en valores permitidos -Suministro de vitamina A en la primera infancia",
    "Error329": "No es válido registrar 'No aplica' en Suministro de Vitamina A en la primera Infancia, para la edad reportada, revise la normatividad vigente.",
    "Error139": "Fecha de toma LDL es mayor a la fecha de corte",
    "Error189": "Fecha de toma LDL es menor o igual a la fecha de nacimiento",
    "Error459": "contenido en el campo Fecha de toma LDL no válido",
    "Error399": "Comodín inválido - Fecha de toma LDL",
    "Error140": "Fecha de toma PSA es mayor a la fecha de corte",
    "Error190": "Fecha de toma PSA es menor o igual a la fecha de nacimiento",
    "Error460": "contenido en el campo Fecha de toma PSA no válido",
    "Error400": "Comodín inválido - Fecha de toma PSA",
    "Error594": "Error en valores permitidos - Preservativos entregados a pacientes con ITS",
    "Error141": "Fecha de tamizaje visual neonatal es mayor a la fecha de corte",
    "Error191": "Fecha de tamizaje visual neonatal es menor a la fecha de nacimiento",
    "Error461": "contenido en el campo Fecha de tamizaje visual neonatal no válido",
    "Error401": "Comodín inválido - Fecha de tamizaje visual neonatal      ",
    "Error142": "Fecha atención en salud bucal por profesional en odontología es mayor a la fecha de corte",
    "Error192": "Fecha atención en salud bucal por profesional en odontología es menor o igual a la fecha de nacimiento",
    "Error402": "Si registra Fecha atención en salud bucal por profesional en odontología, la edad debe ser mayor o igual a 6 meses",
    "Error672": "Comodín inválido - Fecha de atención en salud bucal por profesional en odontología",
    "Error462": "contenido en el campo Fecha de atención en salud bucal por profesional en odontología no válido",
    "Error597": "Registre no aplica en Atención en salud bucal por profesional en odontología si registró no aplica en COP y viceversa",
    "Error669": "Verifique la edad de la persona con Suministro de hierro en la primera Infancia, según normatividad vigente",
    "Error598": "Error en valores permitidos -Suministro de hierro en la primera Infancia ",
    "Error670": "No es válido registrar 'No aplica' en Suministro de hierro en la primera Infancia, para la edad reportada, revise la normatividad vigente.",
    "Error143": "Fecha antígeno de superficie hepatitis B es mayor a la fecha de corte",
    "Error193": "Fecha antígeno de superficie hepatitis B es menor a la fecha de nacimiento",
    "Error429": "contenido en el campo FechaAntigenoSuperficieHepatitisB  no válido",
    "Error403": "Comodín inválido - Fecha antígeno de superficie hepatitis B ",
    "Error341": "Si registra fecha válida para Fecha antígeno de superficie hepatitis B, debe registrar resultado",
    "Error599": "Si registra un comodín que indican no realización o sin dato en Fecha de antígeno de superficie hepatitis B, registre 21 en el resultado",
    "Error600": "Si Resultado antígeno de superficie hepatitis B no aplica, el registro de Fecha antígeno de superficie hepatitis B tampoco aplica",
    "Error601": "Error en valores permitidos - Resultado antígeno de superficie hepatitis B",
    "Error144": "Fecha de toma de la prueba de tamizaje para sífilis es mayor a la fecha de corte",
    "Error194": "Fecha de toma de la prueba de tamizaje para sífilis es menor a la fecha de nacimiento",
    "Error430": "contenido en el campo prueba de tamizaje para sífilis  no válido",
    "Error404": "Comodín inválido - Fecha de toma de la prueba de tamizaje para sífilis",
    "Error344": "Si registra Fecha de toma de la prueba de tamizaje para sífilis, debe registrar resultado de prueba",
    "Error602": "Si registra un comodín que indica no realización o sin dato en Fecha de prueba de tamizaje para sífilis, registre 21 en el resultado",
    "Error603": "Si Resultado de prueba de tamizaje para sífilis no aplica, el registro de Fecha de prueba de tamizaje para sífilis tampoco aplica",
    "Error604": "Error en valores permitidos - Resultado de prueba de tamizaje para sífilis",
    "Error145": "Fecha de toma de prueba para VIH es mayor a la fecha de corte",
    "Error195": "Fecha de toma de prueba para VIH es menor a la fecha de nacimiento",
    "Error431": "contenido en el campo Fecha prueba VIH  no válido",
    "Error405": "Comodín inválido - Fecha de toma de prueba para VIH",
    "Error346": "Si registra fecha de toma de prueba para VIH, debe registrar resultado para prueba de VIH",
    "Error605": "Si registra alguno de los comodines que indican no realización en Fecha de prueba para VIH, registre riesgo no evaluado en el resultado",
    "Error606": "Si fecha de la prueba para VIH no aplica, el registro de resultado de la prueba para VIH tampoco aplica",
    "Error607": "Error en valores permitidos - Resultado de la prueba para VIH",
    "Error350": "Si registra fecha de toma de TSH Neonatal, debe registrar resultado de TSH Neonatal",
    "Error146": "Fecha de TSH neonatal es mayor a la fecha de corte",
    "Error196": "Fecha de TSH neonatal es menor a la fecha de nacimiento",
    "Error432": "contenido en el campo FechaTSHneonatal no válido",
    "Error406": "Comodín inválido - Fecha de TSH neonatal",
    "Error608": "Error en valores permitidos - Resultado de TSH neonatal",
    "Warning068": "Verifique la actividad -Resultado de TSH- realizada en población con edad mayor a 7 días",
    "Error609": "Si Resultado de TSH neonatal es riesgo no evaluado, debe registrar un comodín que indique no realización o sin dato en la fecha del tamizaje ",
    "Error069": "Si registra Tamizaje Cáncer de Cuello Uterino, la edad debe ser mayor o igual a 10 años y el sexo F",
    "Error610": "Si registra Tamizaje cáncer de cuello uterino, debe registrar Fecha tamizaje cáncer de cuello uterino",
    "Error611": "Si reportó la opción de respuesta '1' o '4' en Tamizaje Cáncer de Cuello Uterino, reporte una opción entre 1 a 18 en el Resultado de tamizaje de CaCu",
    "Error612": "Si reportó la opción de respuesta '2' o '3' en Tamizaje Cáncer de Cuello Uterino, reporte la opción '19' o '20' en el Resultado tamizaje de CaCu",
    "Error613": "Si Tamizaje cáncer de cuello uterino no aplica, el registro de Fecha y resultado de tamizaje de cáncer de cuello tampoco aplica",
    "Error614": "Si Registró 21 en Tamizaje cáncer de cuello uterino, debe registrar comodín de no realización o sin dato en Fecha del tamizaje y  21 en el resultado",
    "Error352": "Si registra Fecha de tamizaje cáncer de cuello uterino, debe registrar Resultado tamizaje de cáncer de cuello uterino",
    "Error071": "Si registra Fecha de tamizaje cáncer de cuello uterino, el sexo debe ser F",
    "Error070": "Si registra Fecha de tamizaje cáncer de cuello uterino, la edad debe ser mayor o igual a 10 años",
    "Error147": "Fecha de tamizaje cáncer de cuello uterino es mayor a la fecha de corte",
    "Error197": "Fecha de tamizaje cáncer de cuello uterinoa es menor a la fecha de nacimiento",
    "Error407": "Comodín inválido - Fecha de tamizaje cáncer de cuello uterino",
    "Error072": "Si registra Resultado tamizaje de cáncer de cuello uterino, la edad debe ser mayor o igual a 10 años",
    "Error073": "Si registra Resultado tamizaje de cáncer de cuello, el sexo debe ser F",
    "Error433": "contenido en el campo resultado de tamizaje cáncer de cuello uterino no válido",
    "Error616": "Error en valores permitidos -  Resultado tamizaje de cáncer de cuello",
    "Error354": "Si registra calidad de la muestra, debe registrar resultado de citología",
    "Error615": "Si registra calidad de la muestra es insatisfactoria, el resultado de citología es insatisfactorio para la lectura",
    "Error074": "Si registra Calidad en la Muestra de Citología Cervicouterina, la edad debe ser mayor o igual a 10 años",
    "Error075": "Si registra Calidad en la Muestra de Citología Cervicouterina, el sexo debe ser F",
    "Error022": "La IPS de tamizaje cáncer de cuello uterino no existe",
    "Error076": "Si registra IPS de tamizaje de cáncer de cuello uterino, la edad debe ser mayor a 10 años",
    "Error077": "Si registra IPS de tamizaje de cáncer de cuello uterino, el sexo debe ser F",
    "Error355": "Si registra Código de habilitación IPS tamizaje cáncer de cuello uterino, debe registrar calidad de la muestra",
    "Error078": "Si registra Fecha Colposcopia, la edad debe ser mayor o igual a 10 años",
    "Error079": "Si registra Fecha Colposcopia, el sexo debe ser Femenino",
    "Error148": "Fecha colposcopia es mayor a la fecha de corte",
    "Error198": "Fecha colposcopia es menor a la fecha de nacimiento",
    "Error434": "contenido en el campo FechaColposcopia no válido",
    "Error408": "Comodín inválido - Fecha colposcopia",
    "Error617": "Si registra Fecha válida en Fecha de toma LDL, debe registrar Resultado de LDL",
    "Error618": "Si registró 1800-01-01, 1805-01-01, 1810-01-01, 1825-01-01, 1830-01-01 ó 1835-01-01 en Fecha de toma LDL, registre 998 en Resultado de LDL y viceversa",
    "Error619": "Registre no aplica en Fecha de toma de LDL y Resultado de LDL, a los menores de 29 años sin riesgo cardiovascular identificado",
    "Error083": "Si registra Fecha biopsia cervicouterina, el sexo debe ser Femenino",
    "Error082": "Si registra Fecha biopsia cervicouterina, la edad debe ser mayor a 10 años",
    "Error149": "Fecha biopsia cervicouterina es mayor a la fecha de corte",
    "Error199": "Fecha biopsia cervicouterina es menor a la fecha de nacimiento",
    "Error435": "contenido en el campo fecha biopsia cervicouterina no válido",
    "Error409": "Comodín inválido - Fecha biopsia cervicouterina",
    "Error359": "Si registra resultado de biopsia cervicouterina, debe registrar Fecha biopsia cervicouterina",
    "Error620": "Error en valores permitidos - Resultado de biopsia cervicouterina",
    "Error621": "Si Resultado de biopsia cervicouterina no aplica, el registro de Fecha biopsia cervicouterina tampoco aplica",
    "Error622": "Se registra riesgo no evaluado en Resultado biopsia cervicouterina es sin dato, debe registrar comodín asociado en Fecha de biopsia cervicouterina",
    "Error084": "Si registra Resultado de biopsia cervicouterina, la edad debe ser mayor a 10 años",
    "Error085": "Si registra Resultado de Biopsia Cervical, el sexo debe ser Femenino",
    "Error623": "Si registra fecha válida en Fecha de toma HDL, debe registrar Resultado de HDL",
    "Error624": "Si registró 1800-01-01, 1805-01-01, 1810-01-01, 1825-01-01, 1830-01-01 ó 1835-01-01 en Fecha de toma HDL, registre 998 en Resultado de HDL y viceversa",
    "Error625": "Registre no aplica en Fecha de toma HDL y Resultado de HDL, a los menores de 29 años sin riesgo cardiovascular identificado",
    "Error088": "Registre 'No aplica' en la Fecha de mamografía, si la edad es menor a 35 años",
    "Error089": "Si registra una fecha válida o un comodín en la Fecha de mamografía, el sexo debe ser Femenino",
    "Error150": "Fecha de mamografía es mayor a la fecha de corte",
    "Error200": "Fecha de mamografía es menor a la fecha de nacimiento",
    "Error410": "Comodín inválido - Fecha de mamografía",
    "Error436": "contenido en el campo FechaMamografia no válido",
    "Error362": "Si es mujer mayor o igual de 50 años, no es válido registrar 'no aplica' para mamografía",
    "Error626": "Si es mujer mayor o igual de 50 años y registró un comodín de no realización o sin dato en Fecha de Mamografía, registre 21 en Resultado mamografía",
    "Error361": " Si registra fecha de mamografía, debe registrar resultado de mamografía",
    "Error627": "Si registró 1845-01-01 en Fecha de Mamografía, registre 0 en Resultado mamografía",
    "Error090": "Si registra Resultado mamografía, la edad debe ser mayor o igual a 35 años",
    "Error091": "Si registra Resultado mamografía, el sexo debe ser F",
    "Error364": "Si es menor de 35 años no aplica para resultado de mamografía",
    "Error628": "Error en valores permitidos - Resultado mamografía",
    "Error629": "Si registró Fecha de toma triglicéridos válida, registre el resultado en Resultado triglicéridos.",
    "Error630": "Si registró 1800-01-01, 1805-01-01, 1810-01-01, 1825-01-01, 1830-01-01 ó 1835-01-01 en Fecha toma triglicéridos, registre 998 en Resultado y viceversa",
    "Error631": "Registre no aplica en Fecha de toma triglicéridos y Resultado de triglicéridos, a los menores de 29 años sin riesgo cardiovascular identificado",
    "Error094": "Si registra Fecha de toma biopsia de mama, el sexo debe ser F",
    "Error151": "Fecha de toma biopsia de mama es mayor a la fecha de corte",
    "Error201": "Fecha de toma biopsia mama es menor a la fecha de nacimiento",
    "Error437": "contenido en el campo FechaTomaBiopsiaMama no válido",
    "Error411": "Comodín inválido - Fecha de toma biopsia mama",
    "Error368": "La Fecha de resultado de biopsia de mama es menor a la fecha de toma de la biopsia",
    "Error095": "Si registra Fecha resultado de biopsia de mama, el sexo debe ser F",
    "Error202": "Fecha resultado de biopsia de mama es menor a la fecha de nacimiento",
    "Error152": "Fecha resultado de biopsia de mama es mayor a la fecha de corte",
    "Error632": "Si registra sin dato en Resultado de biopsia de mama, debe registrar sin dato en Fecha de resultado de biopsia",
    "Error369": "Si registra un Resultado de biopsia de mama debe registrar Fecha resultado de biopsia de mama",
    "Error438": "contenido en el campo FechaResultadoBiopsiaMama no válido",
    "Error412": "Comodín inválido - Fecha resultado biopsia mama",
    "Error367": "Si registra sin dato o fecha válida de resultado de biopsia de mama, debe registrar sin dato o el resultado de biopsia de mama",
    "Error633": "Error en valores permitidos - Resultado de Biopsia de mama",
    "Error096": "Si registra Resultado de biopsia de mama, el sexo debe ser F",
    "Error634": "Si registró comodín de no realización o sin dato en Fecha atención en salud bucal a partir de los 6 meses de edad, registre 0 en COP por persona",
    "Error678": "Solo se permite el registro de los valores 0, 21 o un valor de 12 dígitos de longitud",
    "Error635": "Si registró Fecha atención en salud bucal por profesional en odontología, debe registrar el resultado de COP. Si es edéntulo, registre 000000000000.",
    "Error690": "En personas de 6 meses a 4 años 11 meses y 29 días de edad, el rango de valores permitidos para cada componente es entre 00 y 22",
    "Error691": "En personas de 5 años y más de edad, el rango de valores permitidos para cada componente es entre 00 y 32",
    "Error153": "Fecha de toma hemoglobina es mayor a la fecha de corte",
    "Error203": "Fecha de toma hemoglobina es menor a la fecha de nacimiento",
    "Error413": "Comodín inválido - Fecha de toma hemoglobina",
    "Error439": "contenido en el campo FechaHemoglobina no válido",
    "Error638": "Si es mujer entre 10 y 17 años debe registrar una Fecha de toma hemoglobina diferente de 1845-01-01",
    "Warning098": "Si registra resultado para Hemoglobina, este debe estar entre 1,5 y 25",
    "Error639": "Si registró Fecha de toma hemoglobina válida, registre el resultado de la hemoglobina",
    "Error640": "Si es mujer entre 10 y 17 años y registró un comodín de no realización o sin dato en Fecha toma de hemoglobina, registre 998 en Resultado",
    "Error641": "Registró no aplica en Fecha toma de hemoglobina, registre 0 en Resultado de hemogobina",
    "Error642": "Fecha de toma de glicemia basal es mayor a la fecha de corte",
    "Error643": "Fecha de toma de glicemia basal es menor a la fecha de nacimiento",
    "Error440": "contenido en el campo FechaTomaGlicemiaBasal no válido",
    "Error644": "Comodín inválido - Fecha de toma de glicemia basal",
    "Error155": "Fecha creatinina es mayor a la fecha de corte",
    "Error205": "Fecha creatinina es menor a la fecha de nacimiento",
    "Error441": "contenido en el campo FechaCreatinina no válido",
    "Error415": "Comodín inválido - Fecha creatinina",
    "Warning099": "Si registra resultado para Creatinina, este debe estar entre 0.15 y 37",
    "Error371": "Si registra Fecha de toma creatinina, debe registrar el Resultado de creatinina",
    "Error645": "Si registró 1800-01-01, 1805-01-01, 1810-01-01, 1825-01-01, 1830-01-01 ó 1835-01-01 en Fecha toma creatinina, registre 998 en el Resultado y viceversa",
    "Error646": "Registre no aplica en Fecha de toma creatinina y Resultado de creatinina, a los menores de 29 años sin riesgo cardiovascular identificado",
    "Error647": "Error en valores permitidos- Fecha Hemoglobina Glicosilada",
    "Error442": "Contendio en el campo FechaHemoglobinaGlicosilada no válido",
    "Error649": "Si registra Fecha de toma PSA, debe ser hombre mayor de 40 y registrar Resultado PSA",
    "Error650": "Si Resultado de PSA es riesgo no evaluado, debe registrar alguno de los comodines que indican no realización o sin dato en la fecha de PSA",
    "Error651": "Si el sexo es F, registre no aplica en la fecha y el resultado de tacto rectal",
    "Error652": "Si es hombre menor de 40 años, debe registrar  no aplica en el resultado y la fecha de PSA",
    "Error157": "Fecha de toma de tamizaje hepatitis C es mayor a la fecha de corte",
    "Error207": "Fecha de toma de tamizaje hepatitis C es menor a la fecha de nacimiento",
    "Error443": "contenido en el campo fecha de toma de tamizaje hepatitis C no válido",
    "Error417": "Comodín inválido - Fecha de toma de tamizaje hepatitis C",
    "Error158": "Fecha de toma de HDL es mayor a la fecha de corte",
    "Error208": "Fecha de toma de HDL es menor a la fecha de nacimiento",
    "Error444": "contenido en el campo FechaTomaHDL no válido",
    "Error418": "Comodín inválido - Fecha de toma de HDL",
    "Error159": "Fecha de toma de baciloscopia de diagnóstico es mayor a la fecha de corte",
    "Error209": "Fecha de toma de baciloscopia de diagnóstico es menor a la fecha de nacimiento",
    "Error445": "contenido en el campo FechaTomaBaciloscopiaDiagnostico no válido",
    "Error419": "Comodín inválido - Fecha de toma de baciloscopia de diagnóstico",
    "Error375": "Si registra fecha toma de baciloscopia, debe registrar Resultado de baciloscopia diagnóstico. Si aún no tiene el resultado, indique en proceso",
    "Error653": "Error en valores permitidos -  Resultado de baciloscopia diagnóstico",
    "Warning654": "Verifique la actividad -Clasificación del riesgo cardiovascular- se reporta a población mayor a 18 años",
    "Error655": "Error en valores permitidos -Clasificación del riesgo cardiovascular",
    "Error656": "Error en valores permitidos - Tratamiento para sífilis gestacional",
    "Error657": "Error en valores permitidos -  Tratamiento para sífilis congénita",
    "Warning664": "Verifique la actividad -Clasificación de riesgo metabólico- se reporta a población mayor a 18 años",
    "Error665": "Error en valores permitidos -Clasificación de riesgo metabólico",
    "Error666": "Fecha de toma triglicéridos es mayor a la fecha de corte",
    "Error667": "Fecha de toma triglicéridos es menor a la fecha de nacimiento",
    "Error446": "contenido en el campo Fecha de toma triglicéridos no válido",
    "Error668": "Comodín inválido - Fecha de toma triglicéridos",
    "Error211": "Registro repetido en el corte actual"
}